### ISSUE TITLE
Subject tags

### ISSUE THREAD

**Issue by aeakett** [Famicoman/ia-ul-from-youtubedl#2]
It would be great if you could specify the tags on the command line instead of editing the file.

**Comment by Famicoman** [comment]
I agree! I'm planning on doing command line arguments for tags at least. I want to (by default) map the internet archive subject tags directly to the youtube keyword tags (don't have a json sample with those yet) and then give the ability to either overwrite or append to this tag list from what is specified at the command line. This will be in the next version, hopefully with some other optional args.

**Comment by Famicoman** [comment]
FYI, this is almost completed and will be in version 0.2

**Comment by Famicoman** [comment]
Implemented in commit 86fac93f118b2522bfd2a0e8f3d0f255952ad547.
Perform:
python ia-ul-from-youtubedl.py --tags "your;tags;here"
